name: Migrate GitLab Secrets to GitHub

on:
  push:
    paths:
        - 'terraform.tfvars'
  workflow_dispatch:
    # inputs:
    #   gitlab_project_path:
    #     description: 'GitLab project path (e.g., group/project)'
    #     required: true
    #     type: string

jobs:
  migrate_secrets:
    runs-on: ubuntu-latest
    env:
      STATE_FILE: "${{ github.event.repository.name }}.tfstate"
      TF_VAR_github_token: ${{ secrets.GH_PAT }}
      TF_VAR_gitlab_token: ${{ secrets.GL_PAT }}
      TF_VAR_github_owner: ${{ github.repository_owner }}
      TF_VAR_github_repo_name: ${{ github.event.repository.name }}
      TF_VAR_gitlab_project_path: ${{ inputs.gitlab_project_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -state=$STATE_FILE

      - name: Terraform Apply
        run: terraform apply -state=$STATE_FILE -auto-approve

      - name: Upload Terraform State
        uses: actions/upload-artifact@v4
        with:
            name: terraform-state-${{ github.event.repository.name }}
            path: ${{ env.STATE_FILE }}