name: Migrate GitLab to GitHub

on:
  workflow_dispatch:
    inputs:
      confirm_apply:
        description: 'Confirm Terraform apply (yes/no)'
        required: true
        default: 'no'
env:
  TF_VERSION: 1.5.7  # Matches your local version

jobs:
  migrate_secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      #secrets: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Environment Variables
        run: |
          echo "TF_VAR_gitlab_repo=${{ inputs.gitlab_repo }}" >> $GITHUB_ENV
          echo "TF_VAR_github_owner=${{ inputs.github_owner }}" >> $GITHUB_ENV
          echo "TF_VAR_github_repo_name=${{ inputs.github_repo_name }}" >> $GITHUB_ENV
          echo "TF_VAR_gitlab_token=${{ secrets.GL_PAT }}" >> $GITHUB_ENV
          echo "TF_VAR_github_token=${{ secrets.GH_PAT }}" >> $GITHUB_ENV
          echo "WORKSPACE_NAME=${{ inputs.github_repo_name }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          terraform init -backend-config="key=statefiles/${WORKSPACE_NAME}.tfstate" -reconfigure -lock-timeout=5m
        env:
          TF_VAR_gitlab_repo: ${{ env.TF_VAR_gitlab_repo }}
          TF_VAR_github_owner: ${{ env.TF_VAR_github_owner }}
          TF_VAR_github_repo_name: ${{ env.TF_VAR_github_repo_name }}
          TF_VAR_gitlab_token: ${{ env.TF_VAR_gitlab_token }}
          TF_VAR_github_token: ${{ env.TF_VAR_github_token }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan -lock-timeout=5m
        env:
          TF_VAR_gitlab_repo: ${{ env.TF_VAR_gitlab_repo }}
          TF_VAR_github_owner: ${{ env.TF_VAR_github_owner }}
          TF_VAR_github_repo_name: ${{ env.TF_VAR_github_repo_name }}
          TF_VAR_gitlab_token: ${{ env.TF_VAR_gitlab_token }}
          TF_VAR_github_token: ${{ env.TF_VAR_github_token }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_gitlab_repo: ${{ env.TF_VAR_gitlab_repo }}
          TF_VAR_github_owner: ${{ env.TF_VAR_github_owner }}
          TF_VAR_github_repo_name: ${{ env.TF_VAR_github_repo_name }}
          TF_VAR_gitlab_token: ${{ env.TF_VAR_gitlab_token }}
          TF_VAR_github_token: ${{ env.TF_VAR_github_token }}