name: Migrate GitLab to GitHub

on:
  workflow_dispatch:  # Manual trigger without inputs

env:
  TF_VERSION: 1.5.7

jobs:
  migrate_secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For creating the repository
      actions: write   # For managing GitHub Actions variables

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Set Environment Variables
        run: |
          # Set secrets and Azure credentials
          echo "TF_VAR_gitlab_token=${{ secrets.GL_PAT }}" >> $GITHUB_ENV
          echo "TF_VAR_github_token=${{ secrets.GH_PAT }}" >> $GITHUB_ENV
          # Extract Azure credentials from secrets and set as TF_VAR_ variables
          echo "TF_VAR_AZURE_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_AZURE_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_AZURE_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_AZURE_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
          # Debug: Verify values (sensitive data will be masked as ***)
          echo "TF_VAR_AZURE_CLIENT_ID: $TF_VAR_AZURE_CLIENT_ID"
          echo "TF_VAR_AZURE_SUBSCRIPTION_ID: $TF_VAR_AZURE_SUBSCRIPTION_ID"
          echo "TF_VAR_AZURE_TENANT_ID: $TF_VAR_AZURE_TENANT_ID"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
